### ISSUE TITLE
Dataset not available and cannot create a dataset myself.

### ISSUE THREAD

**Issue by ghost** [daitan-innovation/cnn-audio-denoiser#6]
I cannot download the original dataset from the link that has been provided [here](https://github.com/daitan-innovation/cnn-audio-denoiser/blob/master/cdn.daitan.com/dataset.zip) as I am getting 404'd when going to the link that has provided and I've been getting an error when running "create_dataset.py" with python 3.8.

 File "create_dataset.py", line 24, in <module>
    val_dataset.create_tf_record(prefix='value', subset_size=2000)
  File "/home/gabriel/cnn-audio-denoiser/data_processing/dataset.py", line 140, in create_tf_record
    writer = tf.io.TFRecordWriter(tfrecord_filename)
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/tensorflow/python/lib/io/tf_record.py", line 298, in __init__
    super(TFRecordWriter, self).__init__(
tensorflow.python.framework.errors_impl.NotFoundError: ./records/value_0.tfrecords; No such file or directory

If this isn't enough information, please tell me, as I'd be happy to help.

Sincerely,
Gabriel

Edit: creating a folder called records on cnn-denoiser fixed it.

**Comment by sthalles** [comment]
The link has been fixed. 
To create the dataset using 'create_dataset.py' make sure you download the original dataset first.
Att.
